### ISSUE TITLE
作为程序员，请停止你的盗版行为

### ISSUE THREAD

**Issue by mansucache** [quanke/android-studio#1]
作为程序员，做事情应该是有底线的，请停止你的盗版行为，可以参考我的书，但是你不能把我的东西直接拿过来用。这本书毕竟是我花费了很多精力写出来的，被你这样一点点搬过来你觉得合适吗？这跟小偷有什么区别？

**Comment by quanke** [comment]
不好意思，复制的部分我删除重新编写

**Comment by mansucache** [comment]
你写的目录和内容跟我的书大部分相同，请删除或重新编辑。 如果你想做开源，请从自己的角度出发，写自己的东西，如果你把我的东西都搬过来，谁还会买我的书？  毕竟我写了接近两年的东西，花费了大量的精力，我们鼓励开源，但请尊重原创。 谢谢！
